### ISSUE TITLE
Any known implementation of the web frontend?

### ISSUE THREAD

**Issue by bertrik** [MartinVerges/esp32-wifi-manager#4]
This looks like an awesome project, with a solid design, separating the backend logic of AP management and presentation in the web fronted. The one question that I have:

Are there any known implementations of the frontend that combines with this library to form a multi-wifi manager?
Maybe one you wrote, and it can perhaps act as a kind of reference implementation? Or perhaps there is a 3rd-party one that you know of?

**Comment by MartinVerges** [comment]
Hello,

I use it in my onw projects written in svelte. It's not a standalone frontend, but maybe you can use it as reference.

https://github.com/MartinVerges/womolin-waterlevel/blob/main/ui/src/routes/wifi.svelte

Im open to pull requests, so please feel free to add some simple reference if you create one out of it.

Regards
Martin
