### ISSUE TITLE
Preferences.h: No such file or directory

### ISSUE THREAD

**Issue by vanvuongngo** [MartinVerges/esp32-wifi-manager#6]
Hi,

your library looks promising but I got a build failure. Do you have a clue why?
I tried to add the "Preferences by Volodymyr Shymanskyy" library but with that it says to use the native "Preferences":

![image](https://user-images.githubusercontent.com/20791239/210190325-538017d6-a1fd-4597-85d4-ca54dadfe969.png)

after add Preferences v2.0.0 library:
![image](https://user-images.githubusercontent.com/20791239/210190536-4c008244-b683-4622-9124-0666aa00ccd6.png)

**Comment by MartinVerges** [comment]
What was your solution? Anything I need to fix?

**Comment by vanvuongngo** [comment]
Hi Martin, no and thanks for your question. I updated to the latest espressif-idf afterwards it works 👍

**Comment by MartinVerges** [comment]
Great, thanks for the reply!
